# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [3]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

# Let's define a one-dimensional array 
import numpy as np

In [3]:
# Let's create a numpy array from the list "my_list"
my_list = np.array([50,  60,  80, 100, 200, 300, 500, 600])
my_list

array([ 50,  60,  80, 100, 200, 300, 500, 600])

numpy.ndarray

In [5]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8],
                      [7, 3, 6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [8]:
arr = np.array([[3,7,9,3],[4,3,2,2]])
arr

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [10]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)#randomly 20 elements
x

array([0.50610576, 0.23221242, 0.99403281, 0.95172024, 0.4072579 ,
       0.12984464, 0.1240316 , 0.12012183, 0.25104649, 0.25772347,
       0.05149851, 0.1324829 , 0.02967412, 0.83871025, 0.19917565,
       0.62579132, 0.98129035, 0.7105791 , 0.89760922, 0.48623401])

In [7]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)#creating random numbes with 3,3 matrix

array([[0.39727509, 0.98642314, 0.83894724],
       [0.96241275, 0.00115693, 0.05789424],
       [0.34128873, 0.09261359, 0.26125384]])

In [13]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x#print only one int from given range 

41

In [15]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15) #15 random int from 1 to 100
x

array([43, 51, 60, 58, 30, 86, 61, 57, 11, 96, 31, 58, 34, 56, 20])

In [17]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 30)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x#eye print diagonals 

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [25]:
# Matrix of ones
x = np.ones((7,7))#creating matrix of 7 rows and 7 columns 
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [32]:
# Array of zeros
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [62]:
x = int(input("Enter a num"))
arr = np.random.randint(0, x, 10)
arr

Enter a num45


array([14, 26,  5, 39, 27, 14, 23, 19,  8, 18])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [9]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
y = np.arange(11,20)
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
# Add 2 numpy arrays together
sum = x + y
sum#adding to array element by element

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [12]:
square = x**2#squaring of array
square

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
#square roots 
square_roots = np.sqrt(square)
square_roots#finding square roots of the array4e

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
#exponentail 
z = np.exp(y)#exp to find exponentail
z

array([5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
       3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
       1.78482301e+08])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [19]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
#distance formula applied 
z = np.sqrt(X**2 + Y**2)
z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [21]:
my_num = np.array([ 3,  5,  6,  2,  8, 10, 20, 50])
my_num

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [31]:
# Access specific index from the numpy array
my_num[0]#to access element by indexing 
my_num[::-1]#reversing 
my_num[2:4]#fix


array([50,  2])

In [32]:
# Starting from the first index 0 up until and NOT including the last element
my_num[:3]

array([3, 5, 6])

In [34]:
# Broadcasting, altering several values in a numpy array at once
#changing several values 
my_num[0:4] = 7
my_num#broadcasting changing multiple values at ones

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [38]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10,(4, 4))
                        #define range of number 
                        #define size of matrix 
matrix

array([[9, 8, 8, 8],
       [6, 6, 7, 9],
       [6, 1, 3, 4],
       [8, 8, 4, 5]])

In [40]:
# Get a row from a mtrix
#access one row in matrix
matrix[0][2]#row zero(first) 2nd column(3rd column)

8

In [41]:
# Get one element
matrix[1][2]

7

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [45]:
matrix = np.array(([2, 30, 20, -2, -4],
                   [3, 4, 40, -3, -2],
                   [-3, 4, -6, 90, 10],
                   [25, 45, 34, 22, 12],
                   [13, 24, 22, 32, 37]))
matrix[4]=0#replacing entire row with zeros
matrix#we can write matrix[4]/matrix[-1]
    
    
    
   

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [49]:
matrix = np.random.randint(1, 10,(5,5))
matrix

array([[7, 5, 6, 8, 8],
       [7, 3, 2, 8, 6],
       [1, 3, 1, 7, 9],
       [5, 5, 2, 8, 3],
       [2, 1, 7, 3, 2]])

In [51]:
new_matrix = matrix[matrix > 6]
new_matrix

array([7, 8, 8, 7, 8, 7, 9, 8, 7])

In [44]:
# Obtain odd elements only
new

array([3, 9, 9, 9, 9, 1, 3, 3, 1, 1, 3, 1, 3])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [5]:
array = np.array(([2, 30, 20, -2, -4],
                  [3, 4,  40, -3, -2],
                  [-3, 4, -6, 90, 10],
                  [25, 45, 34, 22, 12],
                  [13, 24, 22, 32, 37]))
array[array < 0] = 0
array[array % 2 != 0]= -2
array
                  
    
    
    
    

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [6]:
import pandas as pd

In [7]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
# Creating dataFrame
bank_details = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                            'Bank Client Name': ['Chanel', 'Steve', 'Mitch','Ryan'],
                            'Net worth[$]': [3500, 29000, 10000, 2000],
                            'Years with bank': [3, 4, 9, 5]})
bank_details

Bank Client ID Bank Client Name  Net worth[$]  Years with bank
0             111           Chanel          3500                3
1             222            Steve         29000                4
2             333            Mitch         10000                9
3             444             Ryan          2000                5

In [9]:
# Let's obtain the data type 
type(bank_details)

pandas.core.frame.DataFrame

In [10]:
# you can only view the first couple of rows using .head()
bank_details.head(2)

Bank Client ID Bank Client Name  Net worth[$]  Years with bank
0             111           Chanel          3500                3
1             222            Steve         29000                4

In [11]:
# you can only view the last couple of rows using .tail()
bank_details.tail(1)

Bank Client ID Bank Client Name  Net worth[$]  Years with bank
3             444             Ryan          2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [7]:
portfolio_df = pd.DataFrame({'stock ticker symbols': ['APPL','AMZN','TESLA'],
                            'price of share[$]': [3500, 500, 300],
                            'Number of stocks': [45, 55, 22]})
portfolio_df

stock ticker symbols  price of share[$]  Number of stocks
0                 APPL               3500                45
1                 AMZN                500                55
2                TESLA                300                22

In [16]:
Total_value = portfolio_df['price of share[$]'] * portfolio_df['Number of stocks']
Total_value.sum()

191600

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [62]:
# Pandas is used to read a csv file and store data in a DataFrame


In [21]:
#web scrapping via html
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]#to access list available on that website

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [26]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [64]:
# Read tabular data using read_html


City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [32]:
retirement = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement[0]

HTTPError: HTTP Error 403: Forbidden

# TASK #8: PANDAS OPERATIONS

In [8]:
# Let's define a dataframe as follows:
bank_details = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444],
                            'Bank Client Name': ['Chanel', 'Steve', 'Mitch','Ryan'],
                            'Net worth[$]': [3500, 29000, 10000, 2000],
                            'Years with bank': [3, 4, 9, 5]})
bank_details

Bank Client ID Bank Client Name  Net worth[$]  Years with bank
0             111           Chanel          3500                3
1             222            Steve         29000                4
2             333            Mitch         10000                9
3             444             Ryan          2000                5

In [39]:
# Pick certain rows that satisfy a certain criteria 
loyal = bank_details[bank_details['Years with bank'] >= 5]
loyal

Bank Client ID Bank Client Name  Net worth[$]  Years with bank
2             333            Mitch         10000                9
3             444             Ryan          2000                5

In [44]:
# Delete a column from a DataFrame
del bank_details['Years with bank']
bank_details

Bank Client ID Bank Client Name  Net worth[$]
0             111           Chanel          3500
1             222            Steve         29000
2             333            Mitch         10000
3             444             Ryan          2000

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [50]:
high_netWorth = bank_details[bank_details['Net worth[$]'] >= 5000]
high_netWorth
high_netWorth.sum()

Bank Client ID             555
Bank Client Name    SteveMitch
Net worth[$]             39000
dtype: object

# TASK #9: PANDAS WITH FUNCTIONS

In [9]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [53]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance * 1.2

In [55]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)#to apply a funciton '.apply' use

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [56]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [10]:
def triple_stock(balance):
    return balance*3 + 200

In [15]:
result = bank_client_df['Net worth [$]'].apply(triple_stock)
result
print(result.sum())

134300


# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [80]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [16]:
# You can sort the values in the dataframe according to number of years with bank
# arranging in order 
bank_client_df.sort_values(by= 'Years with bank')# this arrange in order way

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [17]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df#im memory it doesnt change 

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [20]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by='Years with bank', inplace = True)
bank_client_df#using (inplace = True) can data from memory also 

Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [84]:
# Note that now the change (ordering) took place 


Bank client ID Bank Client Name  Net worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [90]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [28]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                  'B': ['B0','B1','B2','B3'],
                  'C': ['C0','C1','C2','C3'],
                  'D': ['D0','D1','D2','D3']},
                 index = [1,2,3,4])
df1

A   B   C   D
1  A0  B0  C0  D0
2  A1  B1  C1  D1
3  A2  B2  C2  D2
4  A3  B3  C3  D3

In [25]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                  'B': ['B4','B5','B6','B7'],
                  'C': ['C4','C5','C6','C7'],
                  'D': ['D4','D5','D6','D7']},
                 index = [5,6,7,8])
df2

A   B   C   D
5  A4  B4  C4  D4
6  A5  B5  C5  D5
7  A6  B6  C6  D6
8  A7  B7  C7  D7

In [26]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                  'B': ['B8','B9','B10','B11'],
                  'C': ['C8','C9','C10','C11'],
                  'D': ['D8','D9','D10','D11']},
                 index = [9,10,11,12])
df3

A    B    C    D
9    A8   B8   C8   D8
10   A9   B9   C9   D9
11  A10  B10  C10  D10
12  A11  B11  C11  D11

In [29]:
pd.concat([df1,df2,df3]) #combing data frame together 
#using [.concat] 

A    B    C    D
1    A0   B0   C0   D0
2    A1   B1   C1   D1
3    A2   B2   C2   D2
4    A3   B3   C3   D3
5    A4   B4   C4   D4
6    A5   B5   C5   D5
7    A6   B6   C6   D6
8    A7   B7   C7   D7
9    A8   B8   C8   D8
10   A9   B9   C9   D9
11  A10  B10  C10  D10
12  A11  B11  C11  D11

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [42]:
raw_data1 = ({'Bank Client ID': ['1','2','3','4','5'],
            'First Name': ['Nacy','Mike','Saksham','sneha','Max'],
            'Last Name': ['singh','Ross','Roy','Rani','well']})
            
Bank_df_1=pd.DataFrame(raw_data1, columns=['Bank Client ID','First Name','Last Name'])
Bank_df_1

Bank Client ID First Name Last Name
0              1       Nacy     singh
1              2       Mike      Ross
2              3    Saksham       Roy
3              4      sneha      Rani
4              5        Max      well

In [44]:
raw_data2 = ({'Bank Client ID': ['6','7','8','9','10'],
            'First Name': ['Nac','Mikes','Saksha','shena','Maxe'],
            'Last Name': ['sing','Rosss','Roy','Rani','well']})
Bank_df_2 = pd.DataFrame(raw_data2, columns=['Bank Client ID', 'First Name','Last Name'])
Bank_df_2

Bank Client ID First Name Last Name
0              6        Nac      sing
1              7      Mikes     Rosss
2              8     Saksha       Roy
3              9      shena      Rani
4             10       Maxe      well

In [47]:
#annual salary
raw_data3 = {'Bank Client ID':['1','2','3','4','5','6','7','8','9','10'],
           'Annual Salary': [10000,34000,45000,56000,45500,12390,223399,34000,67890,345678]}
#to add in data frame
bank_df_salary =pd.DataFrame(raw_data3,columns=['Bank Client ID','Annual Salary'])
bank_df_salary

Bank Client ID  Annual Salary
0              1          10000
1              2          34000
2              3          45000
3              4          56000
4              5          45500
5              6          12390
6              7         223399
7              8          34000
8              9          67890
9             10         345678

In [52]:
bank_df_all=pd.concat([Bank_df_1,Bank_df_2])
bank_df_all

Bank Client ID First Name Last Name
0              1       Nacy     singh
1              2       Mike      Ross
2              3    Saksham       Roy
3              4      sneha      Rani
4              5        Max      well
0              6        Nac      sing
1              7      Mikes     Rosss
2              8     Saksha       Roy
3              9      shena      Rani
4             10       Maxe      well

In [54]:
#bank_client ID is same in both so we can merge 
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all#annual salary mergered

Bank Client ID First Name Last Name  Annual Salary_x  Annual Salary_y
0              1       Nacy     singh            10000            10000
1              2       Mike      Ross            34000            34000
2              3    Saksham       Roy            45000            45000
3              4      sneha      Rani            56000            56000
4              5        Max      well            45500            45500
5              6        Nac      sing            12390            12390
6              7      Mikes     Rosss           223399           223399
7              8     Saksha       Roy            34000            34000
8              9      shena      Rani            67890            67890
9             10       Maxe      well           345678           345678

In [58]:
#adding new client in data frame
new_client = {'Bank Client ID':['11'],
             'First Name': ['Rayn'],
             'Last Name': ['Well'],
             'Annual Salary': [456000]}
new_client_df = pd.DataFrame(new_client, columns=['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary
0             11       Rayn      Well         456000

In [61]:
new_df = pd.concat([bank_df_all, new_client_df])
new_df

Bank Client ID First Name Last Name  Annual Salary_x  Annual Salary_y  \
0              1       Nacy     singh          10000.0          10000.0   
1              2       Mike      Ross          34000.0          34000.0   
2              3    Saksham       Roy          45000.0          45000.0   
3              4      sneha      Rani          56000.0          56000.0   
4              5        Max      well          45500.0          45500.0   
5              6        Nac      sing          12390.0          12390.0   
6              7      Mikes     Rosss         223399.0         223399.0   
7              8     Saksha       Roy          34000.0          34000.0   
8              9      shena      Rani          67890.0          67890.0   
9             10       Maxe      well         345678.0         345678.0   
0             11       Rayn      Well              NaN              NaN   

   Annual Salary  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
5            NaN  
6            NaN  
7            NaN  
8            NaN  
9            NaN  
0       456000.0

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [31]:
x = np.array([[3, 7, 9, 3],
              [4, 3, 2, 2]])
x

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [15]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

Please enter a positive integer value: 7


array([6, 5, 3, 5, 4, 2, 3, 3, 2, 1])

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [22]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

array([10.29563014, 16.55294536, 20.39607805])

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [33]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [34]:
X[4] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [41]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [58]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

stock ticker symbols  price per share [$]  Number of stocks
0                 AAPL                 3500                 3
1                 AMZN                  200                 4
2                    T                   40                 9

In [59]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

0    10500
1      800
2      360
dtype: int64
Total portfolio value = 11660


MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [77]:
def networth_update(balance):
    return balance * 3 + 200 

In [78]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

0    10700
1    87200
2    30200
3     6200
Name: Net worth [$], dtype: int64

In [79]:
results.sum()

134300

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [104]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11         Ry       Aly                    1000

In [105]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Bob                   23000
9             10      Holly   Michelle                   22000
0             11         Ry        Aly                    1000